# Generated by Django 2.1 on 2019-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
    ]
